### ISSUE TITLE
[Request]: Gradle 4.9 compatibility

### ISSUE THREAD

**Issue by k3mist** [cosmicsilence/gradle-scalafix#22]
We have some complex builds with gradle and can't upgrade past 4.9 version due to; 
https://github.com/gradle/gradle/issues/6854
which is also related to
https://github.com/gradle/gradle/issues/6750

I know the plugin is in early development and currently very unlikely to support this. But wanted to ask if it would be possible later?

**Comment by marcelocenerine** [comment]
Thanks @k3mist . We are looking into expanding the range of supported Gradle versions.

**Comment by k3mist** [comment]
@marcelocenerine thank you! also @fsanjuan thank you a ton! really appreciated

**Comment by marcelocenerine** [comment]
This is available in 0.1.4
