### ISSUE TITLE
semanticdb dependency download fails for scala 2.13

### ISSUE THREAD

**Issue by blondacz** [cosmicsilence/gradle-scalafix#23]
Following error is displayed by gradle build for scala 2.13.2 and plugin version 0.1.1. Gradle 5.6.2
```
A problem occurred configuring project 'myproject'.
> Could not create task ':myproject:scalafixMain'.
   > Could not resolve all files for configuration ':myproject:detachedConfiguration1'.
      > Could not find org.scalameta:semanticdb-scalac_2.13.2:4.3.7.
        Searched in the following locations:..
```
There is no 4.3.7  version of semanticdb-scalac for scala 2.13.2. I'm guessing upgrade to latest scalafix would fix this issue.

**Comment by marcelocenerine** [comment]
Hi @blondacz , thanks for reporting this issue. I just released 0.1.2. Please upgrade and see if the error is now gone.
