### ISSUE TITLE
Compatibility with Scala 2.13.4

### ISSUE THREAD

**Issue by maciabit** [cosmicsilence/gradle-scalafix#34]
```
Could not create task ':checkScalafixMain'.
Could not resolve all files for configuration ':detachedConfiguration13'.
Could not find org.scalameta:semanticdb-scalac_2.13.4:4.3.20.
```

Hi, 
The error appear when trying to sync build.gradle.kts, the plugin is imported as follow: 
`id("io.github.cosmicsilence.scalafix") version "0.1.5"`

The problem is that `org.scalameta:semanticdb-scalac_2.13.4:4.3.20` in version 4.3.20 does not exist for Scala 2.13.4.

**Comment by marcelocenerine** [comment]
Hi @maciabi. Thanks for reporting that. I was able to reproduce the issue in one of our integration tests. I believe it will get sorted once #32 is resolved (currently WIP).

**Comment by marcelocenerine** [comment]
@maciabit would you mind giving 0.1.6 a try?
