### ISSUE TITLE
Error running Scalafix after upgrading from 1.5->1.{6,7,8}

### ISSUE THREAD

**Issue by Habitats** [cosmicsilence/gradle-scalafix#43]
When running Scalafix with the following command options
```
gradle scalafix -PautoConfigureSemanticdb=true -Pscalafix.rules=RemoveUnused
```
I now get the error
```
Running Scalafix on 37 Scala source file(s)
error: Unable to load symbol table: error in opening zip file
```
Running with `--info` throws this
```
> Task :scalafixMain FAILED
Caching disabled for task ':scalafixMain' because:
  Caching has not been enabled for the task
Task ':scalafixMain' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Running Scalafix on 37 Scala source file(s)
error: Unable to load symbol table: error in opening zip file
:scalafixMain (Thread[Execution worker for ':' Thread 6,5,main]) completed. Took 0.206 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scalafixMain'.
> Errors:
   - A command-line argument parsed incorrectly

```

It's the same for 1.6, 1.7 and 1.8.

However, 1.5 works fine.

My config looks like this
```
rules = [
  DisableSyntax
]

RemoveUnused.patternvars = true
RemoveUnused.imports = true
RemoveUnused.privates = false
RemoveUnused.locals = false

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = false
DisableSyntax.noReturns = false
DisableSyntax.noWhileLoops = false
DisableSyntax.noAsInstanceOf = false
DisableSyntax.noIsInstanceOf = false
DisableSyntax.noXml = false
DisableSyntax.noDefaultArgs = false
DisableSyntax.noFinalVal = false
DisableSyntax.noFinalize = false
DisableSyntax.noValPatterns = false
DisableSyntax.noUniversalEquality = false
DisableSyntax.noUniversalEqualityMessage = "== and != are unsafe since they allow comparing two unrelated types"
DisableSyntax.regex = []


ExplicitResultTypes.memberKind = [
  Def,
  Val,
  Var
]
ExplicitResultTypes.memberVisibility = [
  Public,
  Protected
]
ExplicitResultTypes.skipSimpleDefinitions = ['Term.Ref', 'Lit', 'Term.New']
ExplicitResultTypes.skipLocalImplicits = true
ExplicitResultTypes.fatalWarnings = false
ExplicitResultTypes.rewriteStructuralTypesToNamedSubclass = true
```

Versions
- Scala 2.12.13
- Oracle Java 1.8.0_251
- Gradle 6.8.3

**Comment by marcelocenerine** [comment]
@Habitats unfortunately I'm not able to reproduce the issue. Is there any particular source file/dependency in your project that causes this error? The main difference in +0.1.6 is this: https://github.com/cosmicsilence/gradle-scalafix/pull/37#discussion_r588950331 . Could you check whether your classpath has any file that is not a jar? See [this issue](https://github.com/scalacenter/scalafix/issues/962)

**Comment by Habitats** [comment]
I do not have anything non-jar on the classpath apart from the `src/main/resources` _folder_ -- which contains a lot of things, but that never gave me problem before?

**Comment by Habitats** [comment]
Assuming this is using the `compileClasspath` not even resources as passed there. Only a bunch of `*.jar` / `*.scala` / `.groovy` / `.java`.

Could that be the issue? That there non-scala code on the classpath?

**Comment by marcelocenerine** [comment]
I wonder if any of the jars you have in the classpath is corrupted. If I add a dependency pointing to a file that is not a jar file or contain invalid content, I get the same error:

```
echo "foo" >  ~/tmp/corrupted.jar
```

`compile files('~/tmp/corrupted.jar')`

```
Running Scalafix on 3 Scala source file(s)
error: Unable to load symbol table: error in opening zip file

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module-a:scalafixMain'.
> Errors:
   - A command-line argument parsed incorrectly
```

Could you run the scalafix task passing `--debug` and search for `Running Scalafix with the following arguments`. The Scalafix task will log all the parameters passed into Scalafix. Take a look at what is printed after `Classpath: ` and see if you can spot anything apart from jars and class file dirs? If you don't, please take a look at [this](https://stackoverflow.com/questions/7600028/maven-error-in-opening-zip-file-when-running-maven) and see if any of the jars you have in the classpath could be corrupted.

**Comment by Habitats** [comment]
After digging deeper into the classpath like you suggested it turned out I had a transitive dependency which incorrectly pulled in a pom-file to the classpath (https://github.com/gradle/gradle/issues/8582)

Excluding netflib from this particular dependency, and forcing a newer version (which didn't include the pom) seems to have solved the issue!

That being said though; I think this could have been solved by simply excluding non-jars from the classpath sent to scalafix? Or would you consider this an upstream issue?

At the very least, the error message could be improved. E.g. list the files that are not jars, or something like that 🤔?

**Comment by marcelocenerine** [comment]
Thanks for confirming that, @Habitats . I couldn't reproduce the same issue with the plugin for Sbt, apparently because Sbt itself already filters out non-jar files from `dependencyClasspath` 🤔 . 

The error message comes from Scalafix and there is not much the plugin can do about that. However, I agree with you that excluding non-jars from the classpath before passing it to Scalafix makes sense.
