### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by gianluca-nitti** [cosmicsilence/gradle-scalafix#60]
Recent scalafix versions [support Scala 3](https://contributors.scala-lang.org/t/scalafix-0-9-28-with-support-for-scala-3/5091).
I'm trying to use this plugin in my project which uses Scala 3 and Gradle. Is this possible?

Using release `0.1.13` of the plugin, I get the following behavior:
* With default options (so with semanticdb autoConfigure = true) compilation fails because the compiler is looking for the semanticdb plugin:
```
> Task :app:compileScala
[Warn] : bad option '-Yrangepos' was ignored
No such entry: plugin.properties
[Warn] : No plugin in path /home/gianluca/.gradle/caches/modules-2/files-2.1/org.scalameta/semanticdb-scalac_2.13.6/4.4.30/87ff27c634c4cecd37f1a41265261f1fd265a71e/semanticdb-scalac_2.13.6-4.4.30.jar
[Error] : bad option: -P:semanticdb:sourceroot:/home/gianluca/MYPROJECT/app
two warnings found
one error found

> Task :app:compileScala FAILED
```
* If I understand correctly, [SemanticDB support is built in the Scala 3 compiler](https://github.com/joan38/mill-scalafix/issues/46#issuecomment-858942933), so there is no plugin which to add. To work around this, I tried disabling the autoConfigure and manually passing the compiler flag needed to enable SemanticDB:
```gradle
// build.gradle
scalafix {
    configFile = file("scalafix.conf")
    semanticdb {
        // this would automatically add compiler flags to generate extra info
        // required by some scalafix rules, but is not compatible with Scala 3
        // so we add them manually (see below)
        autoConfigure = false
    }
}

tasks.withType(ScalaCompile) {
    scalaCompileOptions.additionalParameters = ['-Xsemanticdb'] // for scalafix
}
```
Which however, with semantic rules enabled in `scalafix.conf`, fails with this output:
```
> Task :app:checkScalafixMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkScalafixMain'.
> The semanticdb compiler plugin is required to run semantic rules such as RemoveUnused. To fix this problem, please enable 'semanticdb.autoConfigure' in the plugin extension
```
In my understanding, this is happening because `gradle-scalafix` doesn't know SemanticDB is enabled (due to manually enabling the one built-in the compiler). Can this be fixed or worked around somehow?
* Additionally, if I only use syntactic rules in `scalafix.conf`, I seem to get past the SemanticDB problem but I get parsing errors in files which use certain Scala 3 features such as [extension methods](https://docs.scala-lang.org/scala3/reference/contextual/extension-methods.html). After inspecting the output of `gradle check --debug`, I think the reason could be that it's using a scalafix artifact for Scala 2.13:
```
2021-12-10T00:50:24.536+0100 [DEBUG] [io.github.cosmicsilence.scalafix.ScalafixTask] Running Scalafix with the following arguments:
- Mode: CHECK
- Config file: Optional[/home/gianluca/MYPROJECT/app/scalafix.conf]
- Scalafix cli artifact: ch.epfl.scala:scalafix-cli_2.13.7:0.9.33
- External rules classpath:
- Rules: []
- Scala version: 2.13.6
- Scalac options: [-Xsemanticdb]
```
But I have no idea if and how I can change the scalafix version to use.

**Comment by marcelocenerine** [comment]
@gianluca-nitti support for Scala 3 in Gradle is [relatively recent](https://github.com/gradle/gradle/issues/16527) and this plugin doesn't support that yet 😞 . I don't think there is any workaround you could use... The main problem which affects both syntactic and semantic rules is [this logic to figure out the version of Scala](https://github.com/cosmicsilence/gradle-scalafix/blob/master/src/main/groovy/io/github/cosmicsilence/scalafix/ScalaSourceSet.groovy#L45-L49) used in your project, which doesn't correctly work for Scala 3.

**Comment by marcelocenerine** [comment]
Thanks for bringing this up though. This is something that would be great to add.

Just one note from the [Scalafix docs](https://scalacenter.github.io/scalafix/docs/users/installation.html):
>Scala 3.x: Scala 3 support is experimental and many built-in rules are not supported.

**Comment by gianluca-nitti** [comment]
I understand, thanks for the information.

**Comment by olafurpg** [comment]
> `[Error] : bad option: -P:semanticdb:sourceroot:/home/gianluca/MYPROJECT/app`

The Scala 3 equivalent flag is called `-sourceroot` and `-semanticdb-targetroot` for `-P:semanticdb:targetroot`. One good source of inspiration is the built-in SemanticDB support in sbt https://github.com/sbt/sbt/blob/6c537848266e93674b1de4673c084e8b3f2039df/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L91

> I seem to get past the SemanticDB problem but I get parsing errors in files which use certain Scala 3 features such as extension methods.

@marcelocenerine The Scala 3 dialect should be picked up automatically through the `--scala-version` setting, which seems to be passed correctly here https://github.com/cosmicsilence/gradle-scalafix/blob/master/src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixTask.groovy#L81 cc/ @mlachkar can maybe confirm. Alternatively, it could be that things are working correctly but you're using Scala 3 syntax that's not yet supported by the Scalameta parser (cc/ @tgodzik)

> I think the reason could be that it's using a scalafix artifact for Scala 2.13:

Scalafix supports Scala 3 even if Scalafix itself it still compiled with 2.13. There's on Scala 3 artifact for Scalafix yet.

**Comment by mlachkar** [comment]
In fact Scalafix support scala 3, the only thing we don't have yet is `ExcplicitResultType` working for scala 3.

- We do configure scala 3 dialect using the scala version ([#1392](https://github.com/scalacenter/scalafix/pull/1392)). So if the gradle plugin calls scalafix with the scalaVersion configured, Scalafix will choose the correct dialect. If I remember correctly, we didn't change anything for this part on sbt-scalafix.
- The only change we did on sbt-scalafix, is to configure semanticdb differently for scala3. [#210](https://github.com/scalacenter/sbt-scalafix/pull/210). 

@bjaglin can you please confirm ? Thanks

If you need any help, don't hesitate, I would be happy to help!

**Comment by marcelocenerine** [comment]
Thank you for your prompt response and for sharing all this info, @olafurpg & @mlachkar. I hope get started on this soon 👍
