### ISSUE TITLE
Plugin can't detect Scala version when using Scala 3

### ISSUE THREAD

**Issue by carlosedp** [cosmicsilence/gradle-scalafix#81]
I have a Quarkus project where I use Scala 3 and recently added Scalafix thru the plugin. When I run the task, I get that the plugin couldn't detect the Scala version.

The error I get is:

```
❯ ./gradlew scalafix

> Task :scalafixMain
Running Scalafix on 17 Scala source file(s)

> Task :configSemanticDBQuarkus-generated-sources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':configSemanticDBQuarkus-generated-sources'.
> Failed to calculate the value of task ':configSemanticDBQuarkus-generated-sources' property 'scalaVersion'.
   > Unable to detect the Scala version for the 'quarkus-generated-sources' source set. Please ensure it declares dependency to scala-library or consider adding it to 'ignoreSourceSets'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 34s
12 actionable tasks: 8 executed, 4 up-to-date
```

You can see the config I'm using here: https://github.com/carlosedp/scala3-quarkus-quickstart/pull/45 where the `build.gradle` is at https://github.com/carlosedp/scala3-quarkus-quickstart/blob/5218bf274db3c4c53e06cdc2d9244c9a36dd22b9/build.gradle.

**Comment by carlosedp** [comment]
That worked and I also had to add the generated test sources as:

```
scalafix {
    ignoreSourceSets = [ 'quarkus-generated-sources', 'quarkus-test-generated-sources' ]
}
```

Thanks a lot!

**Comment by carlosedp** [comment]
One thing I found weird that might be related to detecting the Scala version is that it's replacing the `*` wildcard imports with `_` which was the default in Scala 2...

**Comment by marcelocenerine** [comment]
Please have a look at https://github.com/scalacenter/scalafix/issues/1954 . Setting the target dialect for the rule (which, btw, is provided by Scalafix itself) should address this

**Comment by carlosedp** [comment]
Oh thanks! never had to use that as my other projects with Scala Mill usually detected it.

**Comment by marcelocenerine** [comment]
Indeed the rule should be able to infer that provided that the Gradle plugin is passing the necessary parameters. It does pass the Scala version when calling Scalafix (https://github.com/cosmicsilence/gradle-scalafix/blob/master/src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixTask.groovy#L81C35-L81C47). I wonder if could be related to `-Xsource` (see https://github.com/scalacenter/scalafix/blob/main/scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala#L880-L902).

Reopening this issue to investigate it.

**Comment by carlosedp** [comment]
Yea... running with debug I saw:

```
2024-04-22T12:05:36.811-0300 [INFO] [io.github.cosmicsilence.scalafix.ScalafixTask] Running Scalafix with the following arguments:
 - Mode: CHECK
 - Config file: Optional[/Users/cdepaula/repos/scala/scala3-quarkus-quickstart/.scalafix.conf]
 - Scalafix cli artifact: ch.epfl.scala:scalafix-cli_2.13.13:0.12.0
 - External rules classpath:
 - Rules: []
 - Scala version: 3.3.3
 - Scalac options: [-feature, -Wunused:all, -Xsemanticdb, -sourceroot, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart, -Xtarget:8]
 - Source root: /Users/cdepaula/repos/scala/scala3-quarkus-quickstart
 - Sources: [/Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/GreetingResource.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/kafka/ArticleModels.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/kafka/ArticleProcessor.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/kafka/ArticleProducerConsumer.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/TaskResource.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/TaskPageData.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/TaskCreateCommand.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/TaskService.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/TaskViewModel.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/hibernate/Task.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/magnum/UserService.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/magnum/User.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/magnum/UserResource.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/magnum/UserCreateUpdateCommand.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/persistence/magnum/UserPageData.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/org/acme/Main.scala, /Users/cdepaula/repos/scala/scala3-quarkus-quickstart/src/main/scala/helper/Scala3ObjectMapperCustomizer.scala]
```

Maybe the `-Xtarget:8`? I usually don't use Xsource on projects which default to Scala 3...

**Comment by marcelocenerine** [comment]
The issue [here](https://github.com/cosmicsilence/gradle-scalafix/issues/81#issuecomment-2069889170) was that I mistakenly assumed that `Auto` was the default value when, in fact, `StandardLayout` is. Notice [here](https://scalacenter.github.io/scalafix/docs/rules/OrganizeImports.html#standardlayout) that the default setting only does what you expect when the (absolute) source file's path contains `scala-3/` ([code](https://github.com/scalacenter/scalafix/blob/0ff44414c4a477f39a7cc56ea3356c132efbf647/scalafix-rules/src/main/scala/scalafix/internal/rule/OrganizeImports.scala#L80-L85)):

>For files containing **scala-3** in their path,
>- **use \* as wildcard** and as for renames
>- curly braces are stripped for importers with a single imported
>
>For others,
>- **use _ as wildcard** and => for renames
>- curly braces are stripped for importers with a single regular imported

Maybe that is true for the projects you have on Scala Mill. That would explain the difference in behaviour when running the Scalafix rule on Gradle without being explicit about the target dialect.

**Comment by carlosedp** [comment]
I usually have a flat tree on Scala 3 projects as:

```
./
├── benchmarks/
│   └── src/
│       └── Benchmarks.scala
├── examples/
│   └── src/
│       ├── readme-sample.scala
│       ├── receiver-block-until-send.scala
│       ├── select-multiple-channels.scala
│       ├── sender-block-indefinitely.scala
│       ├── separate-loop-methods.scala
│       └── two-senders-receivers.scala
├── zio-channel/
│   ├── src/
│   │   ├── Helpers.scala
│   │   └── Ziochannel.scala
│   └── test/
│       └── src/
│           ├── ChannelSpec.scala
│           ├── HelpersSpec.scala
│           └── TestUtils.scala
├── LICENSE
├── Readme.md
├── build.sc
└── mill*
```

And don't use the `targetDialect` config and it works fine on Mill. Ref. https://github.com/carlosedp/zio-channel

Maybe Mill scalafix plugin detects the version in a different way. Other than that, no problem keeping the `targetDialect = Scala3` in it.

Thanks for looking into it!

**Comment by marcelocenerine** [comment]
>I usually have a flat tree on Scala 3 projects

It also depends on the location in your file system where these projects are checked out. However, it doesn't seem to be the case here.

>And don't use the `targetDialect` config and it works fine on Mill.

I'm unfamiliar with the Mill plugin, but the behaviour of the `OrganizeImports` doesn't seem consistent with what is described in the documentation.

I checked out your project and replaced the `*` wildcards with `_`, informed `targetDialect = Scala3`, and ran `./mill __.fix`, but the wildcards didn't get replaced back to `*` (same the other way around with `targetDialect = Scala2`). If you do the same using the Gradle plugin, it works as expected.

As far as I can tell, the `OrganizeImports` rule is WAI on Gradle.

**Comment by marcelocenerine** [comment]
I believe this explains:

- Your project is using `mill-scalafix` version `0.3.2` ([see](https://github.com/carlosedp/zio-channel/blob/03470c5cc038da03b576a3e18ed489fc8d754bf3/build.sc#L14)) which was released in Jan 2024 ([see](https://github.com/joan38/mill-scalafix/releases)).
- Back then, `mill-scalafix` used version `0.11.1` of Scalafix ([see](https://github.com/joan38/mill-scalafix/blob/3662d3ea86e8512654ed493e1fbde814e83c753e/build.sc#L33))
- Support for `targetDialect` was introduced in Scalafix `0.12.0` ([see](https://github.com/scalacenter/scalafix/commit/9ff33fbbc1f52535b6dd2c504ec26fe211967237))

Latest version of `gradle-scalafix` uses Scalafix `0.12.0`

**Comment by carlosedp** [comment]
Oh, that's it... thanks a lot for digging into it.
I think it's safer to keep `targetDialect = Scala3` since the project is full Scala 3.
Right?

**Comment by marcelocenerine** [comment]
Yes. If you tend to copy/paste the same Scalafix configuration into Scala 2 projects, you could also use `Auto` (assuming the sources are not cross-compiled)
